#!/bin/bash

#SBATCH --nodes=1
#SBATCH --tasks-per-node=40
#SBATCH --time=02:00:00

# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=g.cerro@soton.ac.uk

source activate pyg

python run_lightning.py
